### ISSUE TITLE
Banner ad loads and disappear( triggers loadFailed event) and always shows real ads

### ISSUE THREAD

**Issue by Blast06** [bdlukaa/native_admob_flutter#36] opened 2021-04-04 15:40 UTC
Hi.

I've been trying to implement this package, but im facing some weird behaviour.

**1st:** Banner ads reloads every x time.

This is the code i have:

```
class SymbolsPage extends StatefulWidget {
  @override
  _SymbolsPageState createState() => _SymbolsPageState();
}



class _SymbolsPageState extends State<SymbolsPage> {
  final hc = Get.put(HomeController());

  final ac = Get.find<AdmobController>();

  final TextEditingController nameController = TextEditingController();

  Logger logger = Logger();

  final bannerController = BannerAdController();


  @override
  void initState() { 
    super.initState();
    bannerController.load();

     bannerController.onEvent.listen((e) {
      final event = e.keys.first;
      switch (event) {
        case BannerAdEvent.loading:
          logger.i('BannerAdEvent: loading');
          break;
        case BannerAdEvent.loaded:
          logger.i('BannerAdEvent: loaded');
          break;
        case BannerAdEvent.loadFailed:
          final errorCode = e.values.first;
          logger.i('BannerAdEvent: loadFailed $errorCode');
          break;
        case BannerAdEvent.impression:
          logger.i('BannerAdEvent: ad rendered');
          break;
        default:
          break;
      }
  });
    
  }

  @override
  void dispose() { 
    super.dispose();
    bannerController.dispose();
    

  }

  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.yellow[800],
      appBar: AppBar(
        title: Text('name'),
        backgroundColor: appThemeData.primaryColor,
      ),
      body: GetBuilder<HomeController>(
        builder: (_) => Column(
          children: [
            Container(
              margin: EdgeInsets.only(top: 30, left: 18, right: 18),
              child: CustomSearchText(
                text: hc.nickName,
                enable: true,
                callback: () {
                  nameController.text = hc.nickName;
                  TextSelection.fromPosition(
                    TextPosition(offset: nameController.text.length),
                  );
                  // TODO: Fix bug when generating new nickname and does not change in textbox if focus is on
                },
                controller: nameController,
                callback2: (text) {
                  TextSelection previousSelection = nameController.selection;
             
                  nameController.selection = previousSelection;
                  logger.v("${nameController.selection.start}");
                  _.changeNickName(text);
                },
              ),
            ),

        
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
            
                FlatButton.icon(
                  icon: Icon(Icons.copy_rounded),
                  label: Text('copy'.tr),
                  color: appThemeData.accentColor,
                  onPressed: () {
                    Clipboard.setData(ClipboardData(text: hc.nickName));
                    Get.snackbar("snackbar_download_title".tr,
                        "snackbar_download_message".tr,
                        snackPosition: SnackPosition.BOTTOM,
                        backgroundColor: appThemeData.accentColor);
                  },
                )
              ],
            ),
            const SizedBox(
              height: 10,
            ),
          
            Expanded(
              child: GridView.builder(
                  padding: EdgeInsets.only(left: 8, right: 8),
                  gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    childAspectRatio: 3 / 2,
                    crossAxisSpacing: 20,
                    mainAxisSpacing: 20,
                    crossAxisCount: 4,
                  ),
                  itemCount: symbols2.length,
                  itemBuilder: (BuildContext ctx, index) {
                    return GestureDetector(
                      onTap: () {
                     
                        Get.snackbar("snackbar_download_title2".tr,
                            "snackbar_download_message".tr,
                            snackPosition: SnackPosition.BOTTOM,
                            backgroundColor: appThemeData.accentColor);
                        print("nameController.selection.start");
                        Clipboard.setData(
                            ClipboardData(text: symbols2[index].symbol));
                      },
                      child: Container(
                        alignment: Alignment.center,
                        child: Text(symbols2[index].symbol),
                        decoration: BoxDecoration(
                            color: appThemeData.accentColor,
                            borderRadius: BorderRadius.circular(15)),
                      ),
                    );
                  }),
            ),

            
             BannerAd(controller: bannerController, size: BannerSize.ADAPTIVE),
          ],
        ),
      ),
      bottomNavigationBar: BottomBar(),
    );
  }
}
```

![adchanges](https://user-images.githubusercontent.com/20145023/113513946-fde12f80-9539-11eb-9cb1-8e16b1c06f48.png)
![adchanges2](https://user-images.githubusercontent.com/20145023/113514041-6d571f00-953a-11eb-8146-2a24414308b1.png)

**2nd:** Ads are loaded as production ads or test ads(like random), even though i hardcoded them or, in this case, i retrieve them from my "MyAdmob.class" or wether i place them in the initialize method or straight in the widget's parameter the result is the same.

```
void main() async{
  WidgetsFlutterBinding.ensureInitialized();
  await MobileAds.initialize(
    bannerAdUnitId: MyAdmob.getBannerAdId(),
    interstitialAdUnitId: MyAdmob.getInterstitialAdId(),
    appOpenAdUnitId: MyAdmob.getOpenAdId(),
    
  );
  Get.put(AdmobController());
  // FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;
  // Admob.requestTrackingAuthorization();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  // Locale myLocale;

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'names',
      debugShowCheckedModeBanner: false,
      theme: appThemeData,
      translations: MyTransalations(),
      locale: Get.deviceLocale,
      home: SplashPage(),
      // locale: Get.deviceLocale,
      // translations: MyTransalations(),
    );
  }
}
```

**Comment by bdlukaa** [comment] 2021-04-04 16:16
> 1st: Banner ads reloads every x time.

I see you put your BannerAd inside of a `GetBuilder`, that is supposed to rebuild everytime. BannerAds should be static, so you should do:

```dart
  @override
  Widget build(BuildContext context) {
      final bannerAd = BannerAd(controller: bannerController, size: BannerSize.ADAPTIVE);
      return GetBuilder(
        builder: (_) => Column(
            children: [
                ..., // all the other widgets
                bannerAd,
            ]
        )
      );
  }
```

**Comment by bdlukaa** [comment] 2021-04-04 16:19
> 2nd: Ads are loaded as production ads or test ads(like random)

Are you running on an emulator? If not, make sure to [add your device as a test device](https://github.com/bdlukaa/native_admob_flutter/wiki/Initialize#add-your-test-device-programmatically)

You can also set the id at the constructor of each ad.

**Comment by Blast06** [comment] 2021-04-04 21:00
Thanks for the quick answer!


1st: I already added the device as a test device, a couple months ago (through admob).
I also set the id on the constructor of each ad, but it does not work. 


2nd: It keeps reloading, it even shows test ads to production ads when reloads. Tried programmatically, same result.
![photo_2021-04-04_16-57-54](https://user-images.githubusercontent.com/20145023/113521373-174ca080-9567-11eb-9f09-e8c9773e25c2.jpg)

**Comment by bdlukaa** [comment] 2021-04-04 21:16
> 1st: same result.

Can you show the code for `MyAdmob.getBannerAdId(),`?

> 2nd: It keeps reloading, it even shows test ads to production ads when reloads.

Can you try adding an [AutomaticKeepAliveClientMixing](https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html) to your page?

**Comment by Blast06** [comment] 2021-04-04 22:03
1st: Sure. If it's worth i was using the same code with other packages but that did not happened.

```
const TEST = true;

class MyAdmob {
  //TEST
  static final String TEST_app_id_ios =
      'ca-app-pub-2334510780816542~6726672523';
  static final String TEST_app_id_android =
      'ca-app-pub-2334510780816542~7385148076';
  static final String TEST_banner_id_ios =
      'ca-app-pub-3940256099942544/2934735716';
  static final String TEST_banner_id_android =
      'ca-app-pub-3940256099942544/6300978111';
  static final String TEST_interstitial_id_ios =
      'ca-app-pub-3940256099942544/4411468910';
  static final String TEST_interstitial_id_android =
      'ca-app-pub-3940256099942544/1033173712';

  static final String TEST_open_ad_id_android =
      'ca-app-pub-3940256099942544/3419835294';
  static final String TEST_open_ad_id_ios =
      'ca-app-pub-3940256099942544/3419835294';

  //PROD
  static final String PROD_app_id_ios =
      'ca-app-pub-4473546092325949~3852512696';
  static final String PROD_app_id_android =
      'ca-app-pub-4473546092325949~7701039588';
  static final String PROD_banner_id_ios =
      'ca-app-pub-4473546092325949/1034777663';
  static final String PROD_banner_id_android =
      'ca-app-pub-4473546092325949/1106683403';
  static final String PROD_interstitial_id_ios =
      'ca-app-pub-4473546092325949/5977496040';
  static final String PROD_interstitial_id_android =
      'ca-app-pub-4473546092325949/7977432875';
  static final String PROD_open_ad_id_android =
      'ca-app-pub-4473546092325949/4883304558';
  static final String PROD_open_ad_id_ios =
      'ca-app-pub-3940256099942544/3419835294';

  static String getAppName() {
    if (Platform.isAndroid) {
      return 'My App';
    } else {
      return 'My App on ios';
    }
  }


  static String getAdMobAppId() {
    if (Platform.isIOS) {
      return TEST ? MyAdmob.TEST_app_id_ios : MyAdmob.PROD_app_id_ios;
    } else if (Platform.isAndroid) {
      return TEST ? MyAdmob.TEST_app_id_android : MyAdmob.PROD_app_id_android;
    }
    return null;
  }

  static String getBannerAdId() {
    if (Platform.isIOS) {
      // return ;
      return TEST ? MyAdmob.TEST_banner_id_ios : MyAdmob.PROD_banner_id_ios;
    } else if (Platform.isAndroid) {
      // return ;
      return TEST
          ? MyAdmob.TEST_banner_id_android
          : MyAdmob.PROD_banner_id_android;
    }
    return null;
  }

  static String getInterstitialAdId() {
    if (Platform.isIOS) {
      return TEST
          ? MyAdmob.TEST_interstitial_id_ios
          : MyAdmob.PROD_interstitial_id_ios;
    } else if (Platform.isAndroid) {
      return TEST
          ? MyAdmob.TEST_interstitial_id_android
          : MyAdmob.PROD_interstitial_id_android;
    }
    return null;
  }

static String getOpenAdId() {
    if (Platform.isIOS) {
      return TEST
          ? MyAdmob.TEST_open_ad_id_ios
          : MyAdmob.PROD_open_ad_id_ios;
    } else if (Platform.isAndroid) {
      return TEST
          ? MyAdmob.TEST_open_ad_id_android
          : MyAdmob.PROD_open_ad_id_android;
    }
    return null;
  }
}
```
2nd: Added it, but it keeps happening.

**Comment by bdlukaa** [comment] 2021-04-04 22:10
> 2nd: Added it, but it keeps happening.

Can you try to remove it from `GetBuilder`?

> 1st: Sure. If it's worth i was using the same code with other packages but that did not happened.

As far as I can tell by your code, you're not using null-safety. Are you using the lastest version of the package: [1.2.0](https://pub.dev/packages/native_admob_flutter)?

**Comment by Blast06** [comment] 2021-04-06 00:05
> Can you try to remove it from GetBuilder?

Did it, but keeps happening.

> As far as I can tell by your code, you're not using null-safety. Are you using the lastest version of the package: 1.2.0?

You're right, im not using it, the package version i guess it's below 1.2.0 ( because im not specifying it)

**Comment by bdlukaa** [comment] 2021-04-06 01:30
I think this issue was fixed in version [1.0.0](https://pub.dev/packages/native_admob_flutter/changelog#100-pre---ios-update---00032021)

**Comment by Blast06** [comment] 2021-04-06 18:41
Great, upgrade it to the last version with null-safety along with the project

The ads keep switching between test-prods.

Keeps reloading, but very very quick, and on the log console it doesn't say 'loadFailed' anymore, just re rendered(dont know if that's ok)

![adchanges4](https://user-images.githubusercontent.com/20145023/113754850-a8de1e80-96dd-11eb-976b-b8f20f654527.png)

**Comment by bdlukaa** [comment] 2021-04-06 19:28
Can you try changing the banner ad options?

```dart
BannerAd(
  options: BannerAdOptions(
    reloadWhenSizeChanges: false,
    reloadWhenUnitIdChanges: false,
  )
)
```

Also, do you need the controller? If not, can you try to remove it to see if it solves?

**Comment by Blast06** [comment] 2021-04-07 00:36
Changed the banner's options, removed the whole controller , but it keeps reloading.

**Comment by bdlukaa** [comment] 2021-04-07 00:58
Sorry but I can't reproduce. Can you try to run the example app and see if it runs?

**Comment by Blast06** [comment] 2021-04-07 19:22
Tried with example app, but same result.

**Comment by bdlukaa** [comment] 2021-04-08 15:14
> The ads keep switching between test-prods.

Can you try using the test APP id while testing?

[Android](https://github.com/bdlukaa/native_admob_flutter/wiki/Platform-setup#update-your-androidmanifestxml)
[iOS](https://github.com/bdlukaa/native_admob_flutter/wiki/Platform-setup#update-your-infoplist)

> Keeps reloading, but very very quick, and on the log console it doesn't say 'loadFailed' anymore, just re rendered(dont know if that's ok)

If it doesn't affect performance, it's ok. You can track performance by using devtools

**Comment by Blast06** [comment] 2021-04-09 12:35
> Can you try using the test APP id while testing?

That's the deal, i've been using them since the beginning which is kind of weird.

> If it doesn't affect performance, it's ok. You can track performance by using devtools

Oh, that's great, i was worried because i thought Admob could do something about it. If it's for performance, im ok with it.

**Comment by bdlukaa** [comment] 2021-04-09 14:26
> i thought Admob could do something about it

It only does something if you click your own production ads. You can load as many ads as you want

**Comment by bdlukaa** [comment] 2021-04-09 14:27
I'll keep this issue open in case of someone has the same issue and may provide more info.

**Comment by Tetracyl** [comment] 2021-04-12 14:49
I'm also having the same issue where banner ads keep reloading every couple of seconds.

Code:

```
  ScrollController scrollController = ScrollController();
  BannerAdController bannerAdController = BannerAdController();

  @override
  void dispose() {
    bannerAdController.dispose();
    scrollController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    bannerAdController.onEvent.listen((e) {
      final event = e.keys.first;
      switch (event) {
        case BannerAdEvent.loading:
          print('loading');
          break;
        case BannerAdEvent.loaded:
          print('loaded');
          break;
        case BannerAdEvent.loadFailed:
          final errorCode = e.values.first;
          print('loadFailed $errorCode');
          break;
        case BannerAdEvent.impression:
          print('ad rendered');
          break;
        default:
          break;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: appBarWidget('global.app_bar.explore'.tr(), context),
      body: SafeArea(
        child: CupertinoScrollbar(
          controller: scrollController,
          child: SingleChildScrollView(
            scrollDirection: Axis.vertical,
            controller: scrollController,
            child: FutureBuilder(
              future: GetManager.getTags(),
              builder: (context, res) {
                return Column(
                  children: [
                    BannerAd(
                      controller: bannerAdController,
                      builder: (context, child) {
                        return Container(
                          child: child,
                        );
                      },
                      size: BannerSize.ADAPTIVE,
                      nonPersonalizedAds: true,
                      unitId: AdHelper.explore,
                    ),
```

Console:
```
I/flutter (23709): ad rendered
I/flutter (23709): loaded
I/Ads     (23709): This request is sent from a test device.
V/InputMethodManager(23709): b/117267690: Failed to get fallback IMM with expected displayId=158 actual IMM#displayId=0 view=com.google.android.gms.internal.ads.zzbfy{89322d2 VFEDHVC.. ........ 0,0-1438,224}   
E/BufferQueueProducer(23709): [SurfaceTexture-0-23709-56](id:5c9d0000003b,api:1,p:378,c:23709) dequeueBuffer: BufferQueue has been abandoned
E/chromium(23709): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
I/flutter (23709): loaded
I/flutter (23709): ad rendered
I/Ads     (23709): This request is sent from a test device.
E/chromium(23709): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
V/InputMethodManager(23709): b/117267690: Failed to get fallback IMM with expected displayId=159 actual IMM#displayId=0 view=com.google.android.gms.internal.ads.zzbfy{6a66fb VFEDHVC.. ........ 0,0-1438,224}    
I/flutter (23709): loaded
I/flutter (23709): ad rendered
W/Ads     (23709): #004 The webview is destroyed. Ignoring action.
W/Ads     (23709): #004 The webview is destroyed. Ignoring action.
I/Ads     (23709): This request is sent from a test device.
E/chromium(23709): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
V/InputMethodManager(23709): b/117267690: Failed to get fallback IMM with expected displayId=159 actual IMM#displayId=0 view=com.google.android.gms.internal.ads.zzbfy{d40702a VFEDHVC.. ........ 0,0-1438,224}   
I/flutter (23709): loaded     
I/flutter (23709): ad rendered
W/Ads     (23709): #004 The webview is destroyed. Ignoring action.
W/Ads     (23709): #004 The webview is destroyed. Ignoring action.
E/chromium(23709): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
V/InputMethodManager(23709): b/117267690: Failed to get fallback IMM with expected displayId=159 actual IMM#displayId=0 view=com.google.android.gms.internal.ads.zzbfy{312a61f VFEDHVC.. ........ 0,0-1438,224}   
I/flutter (23709): loaded     
I/flutter (23709): ad rendered
W/Ads     (23709): #004 The webview is destroyed. Ignoring action.
W/Ads     (23709): #004 The webview is destroyed. Ignoring action.
```

**Comment by bdlukaa** [comment] 2021-04-12 16:18
This seems to be an issue with the way Banner Ad was implemented. I'll try to rework on banner ads to make them like Native Ads.

Tho, BannerAds shouldn't be on updatable widgets, such as FutureBuilder, try to moving them out of it.

**Comment by bdlukaa** [comment] 2021-04-12 16:59
I could reproduce this issue when using the following code inside of a `ListView`:

```dart
        ...List.generate(10, (index) {
            return BannerAd(
              builder: (context, child) {
                return Container(
                  padding: EdgeInsets.symmetric(vertical: 10),
                  color: Colors.black,
                  child: child,
                );
              },
              loading: Text('loading'),
              error: Text('error'),
              size: BannerSize.ADAPTIVE,
            );
          }),
```

**Comment by Tetracyl** [comment] 2021-04-12 17:26
> 
> 
> This seems to be an issue with the way Banner Ad was implemented. I'll try to rework on banner ads to make them like Native Ads.
> 
> Tho, BannerAds shouldn't be on updatable widgets, such as FutureBuilder, try to moving them out of it.

I tried removing the Banner ad out of the FutureBuilder and it still keeps reloading. 

Is it possible that my admob account could be limited if the ad keeps reloading? I want to push an update to my app and I'm not sure if this reload bug will effect anything.

**Comment by bdlukaa** [comment] 2021-04-12 17:29
@Tetracyl Hey, can you try to use the latest master to see if the issue was fixed?

```yaml

dependencies:
  native_admob_flutter:
    git:
      url: https://github.com/bdlukaa/native_admob_flutter.git
```

**Comment by Tetracyl** [comment] 2021-04-12 17:34
Still experiencing the same issue with the latest master.

**Comment by bdlukaa** [comment] 2021-04-12 17:41
I actually think this is not a problem with the plugin itself, because admob automatically refresh ads:

![](https://i.stack.imgur.com/VpO6V.png)

Can you try to set it to no refresh?

I'm testing with banner ads and they reload at each 60 seconds. I think this is expected!

**Comment by bdlukaa** [comment] 2021-04-12 17:43
And on the latest `pub` version, the ad load request is done only once at BannerAd's `initState`, which complements it not being an issue with the plugin itself!

**Comment by Tetracyl** [comment] 2021-04-12 17:49
You're right, it's not an issue with the package so I'm going to keep it as Google Optimized.

![image](https://user-images.githubusercontent.com/29833473/114438494-ad428580-9b7c-11eb-8de4-0f1bf21ce0f9.png)

**Comment by bdlukaa** [comment] 2021-04-12 17:50
As said on https://support.google.com/admob/answer/3245199?hl=en

> # Banner ads
> We recommend using the Google-optimized automatic refresh rate. The optimized rate is calculated using AdMob historical data to ensure the ads shown in your ad units are being refreshed at the best rate for banner ads.
> 
> You may also set a custom refresh rate of 30-120 seconds or disable refresh rate completely.
> # Native ads
> Refresh rate is disabled by default for native ads. Native ads should complement the content and environment surrounding them. Refreshing native ads regularly may interfere with the look, feel, and cohesiveness of an app.

With the above being said, and the same not happening with Native Ads, this should not be a problem with this plugin.

When creating a new banner ad unit id, press 'Advanced Settings' and customize the Automatic Refresh rate. If you want the ad to not reload, set it to disabled.

Closing this as invalid.

**Closed by bdlukaa** 2021-04-12 17:50 UTC
Labels: Banner Ad, invalid
