### ISSUE TITLE
RewardedAdEvent.earnedReward did not get fired even after ads finish showing and closed.

### ISSUE THREAD

**Issue by zenkog** [bdlukaa/native_admob_flutter#56] opened 2021-05-06 16:40 UTC
This only happens in iOS.

My code:

```
void _onRewardAdEvent(Map<RewardedAdEvent, dynamic> adEvents) {
    try {
      final event = adEvents.keys.first;

      switch (event) {
        case RewardedAdEvent.loading:
          break;
        case RewardedAdEvent.loaded:
          print('*** Ad Loaded!');
          setState(() {
            isAdsLoading = false;
          });
          break;
        case RewardedAdEvent.loadFailed:
          final error = adEvents.values.first;
          print('Error Rewarded Video Ad failed to load: $error');
          break;
        case RewardedAdEvent.showed:
          print('*** Ad showed');

          break;
        case RewardedAdEvent.showFailed:
          final error = adEvents.values.first;
          print('show failed $error');
          break;
        case RewardedAdEvent.closed:
          print('*** Ad closed');
          if (!isRewardGiven) {
            setState(() {
              isAdsLoading = true;
            });
            if (_rewardedAd != null && !_rewardedAd.isAvailable) _rewardedAd.load();
          }
          break;
        case RewardedAdEvent.earnedReward:
          print('*** Rewarded Ad successful.');

          isRewardGiven = true;
          
          // Give reward here

          break;
        default:
          break;
      }
    } catch (error) {
      print('Error in _onRewardedAdEvent: $error');
      BlocProvider.of<IapCubit>(context).onErrorCaught(error);
    }
  }
```

As you can see that I will print out to debug console for every event being fired.
So I open the app, and after the ads was loaded, I watched it until the end then tap the x button to close it.

But this is what I get in the Debug Console

```
WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
WF: _WebFilterIsActive returning: NO
flutter: *** Ad Loaded!
flutter: *** Ad showed
flutter: *** Ad closed
```

As you can see that `RewardedAdEvent.earnedReward` never gets fired.
In Android, after I tap the x button to close the ad, the reward will be given and all is well.
But with iOS, it just stops there and the `RewardedAdEvent.earnedReward` is not fired.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.2 20D80 darwin-x64, locale en-US)
    • Flutter version 2.0.5 at /Users/ME/development/flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Volumes/ME/Applications/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Volumes/ME/Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • iPho (mobile) • bcccbe93864b12b2d3422cdbaecf25da9ac75d28 • ios            • iOS 14.4.2
    • Chrome (web)        • chrome                                   • web-javascript • Google
      Chrome 90.0.4430.93

• No issues found!

```
</details>

**Comment by bdlukaa** [comment] 2021-05-06 16:45
Duplicate of https://github.com/bdlukaa/native_admob_flutter/issues/40

**Closed by bdlukaa** 2021-05-06 16:45 UTC
Labels: duplicate
