### ISSUE TITLE
Preloading native and banner ads

### ISSUE THREAD

**Issue by cabdirashiid-developer** [bdlukaa/native_admob_flutter#72] opened 2021-06-02 18:14 UTC
Native and banner ad widgets takes seconds to build and show.  It may be missed when fast scrolling listview. 

Is there function similar to .show() ?

**Comment by bdlukaa** [comment] 2021-06-02 19:33
You can use the controller (native and banner) to preload the ads.

The banner and native ads use platform views to display the ads. These platforms views take a while to be loaded (at about 1 second)

Duplicate of #18

**Closed by bdlukaa** 2021-06-02 19:33 UTC
Labels: duplicate

**Comment by cabdirashiid-developer** [comment] 2021-06-02 21:55
I did preload them with controllers. The issue is there's a delay on ad widget build. The loading widget takes seconds.

Also I noticed media view in native ads that wasn't clickable might be a video. It showed a play button after sometime.
