### ISSUE TITLE
Banner Ads receiving BannerAdEvent.loading: null even with Test Ads

### ISSUE THREAD

**Issue by nemoryoliver** [bdlukaa/native_admob_flutter#15] opened 2021-02-24 21:55 UTC
Also, sometimes when I get this I get a black only Ad with the Test Ads name on the top center.

**Comment by bdlukaa** [comment] 2021-02-24 22:26
`BannerAdEvent.loading: null` means the ad is still loading. It'll result in a `BannerAdEvent.loaded: int` or in a `BannerAdEvent.loadError: AdError`. You can [listen to events](https://github.com/bdlukaa/native_admob_flutter/wiki/Using-the-controller-and-listening-to-banner-events#listening-to-events) to track the things that happens on the ad

> I get a black only Ad with the Test Ads name on the top center.

I also get this. I think it's normal. 

I'll be closing this issue

**Closed by bdlukaa** 2021-02-24 22:26 UTC

**Comment by nemoryoliver** [comment] 2021-02-24 22:37
> `BannerAdEvent.loading: null` means the ad is still loading. It'll result in a `BannerAdEvent.loaded: int` or in a `BannerAdEvent.loadError: AdError`. You can [listen to events](https://github.com/bdlukaa/native_admob_flutter/wiki/Using-the-controller-and-listening-to-banner-events#listening-to-events) to track the things that happens on the ad
> 
> > I get a black only Ad with the Test Ads name on the top center.
> 
> I also get this. I think it's normal.
> 
> I'll be closing this issue

Okay great! Thanks a lot

**Comment by nemoryoliver** [comment] 2021-02-24 22:46
Also, It would be great to add a loading timeout for Banners, I'm currently testing mine's been loading for more than 5 minutes already. Still the only event I received is BannerAdEvent.loading:null

**Comment by bdlukaa** [comment] 2021-02-25 20:55
> Also, It would be great to add a loading timeout for Banners

I just published a new version that adds this funcionality to all the ads: [v0.9.3](https://pub.dev/packages/native_admob_flutter)

**Comment by bdlukaa** [comment] 2021-02-27 22:14
> I'm currently testing mine's been loading for more than 5 minutes already.

I just released a new version that is supposed to fix this issue: [v0.9.4](https://pub.dev/packages/native_admob_flutter)
See [this](https://github.com/bdlukaa/native_admob_flutter/issues/16) for more information on the cause of the problem
