### ISSUE TITLE
real ads are not loading error :3 but test ads are working fine 

### ISSUE THREAD

**Issue by SureshKumar311** [bdlukaa/native_admob_flutter#39] opened 2021-04-13 14:48 UTC
```
**Main dart**

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await MobileAds.initialize(
      // nativeAdUnitId: "xxxxxxx",
      interstitialAdUnitId: "xxxxxx");

  MobileAds.setTestDeviceIds(['xxxxxxx']);
  //Admob.initialize();
  await Firebase.initializeApp();
  await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;

  await FlutterDownloader.initialize(
      // debug: true // optional: set false to disable printing logs to console
      );
  await Permission.storage.request();

  runZoned(() {
    runApp(Appui());
  });
}



**my ads page code :::::**

 final interstitialAd =
      InterstitialAd(unitId: "ca-app-pub-2820502455308437/3641680546");

 @override
  void initState() {
    if (!interstitialAd.isLoaded) interstitialAd.load();
    interstitialAd.onEvent.listen((e) {
      final event = e.keys.first;
      switch (event) {
        case FullScreenAdEvent.closed:
          // Here is a handy place to load a new interstitial after displaying the previous one
          interstitialAd.load();
          // Do not show an ad here
          break;
        default:
          break;
      }
    });
    super.initState();
  }


**show ads** 
  IconButton(
                icon: Icon(Icons.ac_unit),
                onPressed: () async {
                  if (interstitialAd.isLoaded) {
                    await interstitialAd.show();
                  } else {
                    await interstitialAd.load();
                  }
                },
              ),

and native ads also same 


**error ::**

D/DynamitePackage( 7730): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     ( 7730): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("02A6AAB51B2AB59A326BCEA37FF7306A")) to get test ads on this device.
I/DynamiteModule( 7730): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210402101
I/DynamiteModule( 7730): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210402101
I/DynamiteModule( 7730): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210402101
I/DynamiteModule( 7730): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210402101
2
D/AudioManager( 7730): getStreamVolume isRestricted mode = 0
I/Ads     ( 7730): Ad failed to load : 3

```

**Comment by SureshKumar311** [comment] 2021-04-13 14:49
**i had create model class for native ads but same issue  plz help me** 

import 'package:lottie/lottie.dart';
import 'package:native_admob_flutter/native_admob_flutter.dart';
import 'package:flutter/material.dart';

// unitId: "ca-app-pub-2820502455308437/9671956178"
// unitId: "ca-app-pub-2820502455308437/3641680546"
class Admodel {
  final controller = NativeAdController();
  final interstitialAd = InterstitialAd();
  final interstitialVideoAd = InterstitialAd()
    ..load(unitId: MobileAds.interstitialAdVideoTestUnitId);
  Color bg1;
  Color bg2;
  final rewardedAd = RewardedAd()..load();

  final AppOpenAd appOpenAd = AppOpenAd(timeout: Duration(seconds: 3))..load();
  Admodel({
    MaterialColor bg1c = Colors.purple,
    int bg1v = 300,
    MaterialColor bg2c = Colors.purple,
    int bg2v = 900,
    bool nativeadenable = true,
    bool interstitialadenable = false,
  }) {
    this.bg1 = bg1c[bg1v];
    this.bg2 = bg2c[bg2v];
    nativeadenable
        ? controller.load()
        : interstitialadenable
            ? interstitialAd.load()
            : interstitialVideoAd.isAvailable;

    if (!interstitialAd.isLoaded) interstitialAd.load();
    interstitialAd.onEvent.listen((e) {
      final event = e.keys.first;
      switch (event) {
        case FullScreenAdEvent.closed:
          // Here is a handy place to load a new interstitial after displaying the previous one
          interstitialAd.load();
          // Do not show an ad here
          break;
        default:
          break;
      }
    });
    appOpenAd.onEvent.listen((e) => print(e));
  }

  native({
    double height: 150,
  }) {
    return Container(
      height: height,
      child: NativeAd(
        builder: (context, child) {
          return Container(
            child: child,
          );
        },
        buildLayout: adbuilder,
        loading: Lottie.asset("assets/loading.json"),
        error: Lottie.asset("assets/page-error.json"),
        //Text('Error in ADs Server \n Please report to developer'),
        icon: AdImageView(size: 100, padding: EdgeInsets.all(5)),
        ratingBar: AdRatingBarView(elevationColor: Colors.white, height: 20),
        store: AdTextView(
          style: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.normal,
            color: Colors.amber[300],
          ),
        ),
        button: AdButtonView(
          pressColor: Colors.white,
          padding: EdgeInsets.all(10),
          textStyle: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Colors.black54,
              letterSpacing: 0.3),
        ),
        headline: AdTextView(
          style: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
          maxLines: 1,
        ),
        media: AdMediaView(height: 80, width: 120),
      ),
    );
  }

  AdLayoutBuilder get adbuilder => (ratingBar, media, icon, headline,
          advertiser, body, price, store, attribution, button) {
        return AdLinearLayout(
          gravity: LayoutGravity.center,
          padding: EdgeInsets.all(10),
          // The first linear layout width needs to be extended to the
          // parents height, otherwise the children won't fit good
          height: MATCH_PARENT,
          width: MATCH_PARENT,
          orientation: HORIZONTAL,
          decoration: AdDecoration(
            gradient: AdRadialGradient(
              colors: [bg1, bg2],
              center: Alignment(0.5, 0.5),
              radius: 1000,
            ),
          ),

          children: [
            icon,
            AdLinearLayout(
              gravity: LayoutGravity.left,
              padding: EdgeInsets.fromLTRB(20, 0, 0, 0),
              // height: 0.5,
              children: [
                headline,
                AdLinearLayout(
                  gravity: LayoutGravity.left,
                  padding: EdgeInsets.fromLTRB(0, 10, 0, 0),
                  children: [
                    attribution,
                    AdLinearLayout(
                      gravity: LayoutGravity.left,
                      padding: EdgeInsets.fromLTRB(10, 0, 0, 0),
                      children: [
                        ratingBar,
                        advertiser,
                        AdLinearLayout(
                          gravity: LayoutGravity.left,
                          padding: EdgeInsets.fromLTRB(10, 0, 0, 0),
                          children: [store],
                          orientation: HORIZONTAL,
                          width: WRAP_CONTENT,
                        ),
                      ],
                      orientation: HORIZONTAL,
                      width: WRAP_CONTENT,
                    ),
                  ],
                  orientation: HORIZONTAL,
                  width: WRAP_CONTENT,
                ),
                AdLinearLayout(
                  gravity: LayoutGravity.left,
                  padding: EdgeInsets.fromLTRB(0, 10, 10, 3),
                  children: [
                    button,
                  ],
                  width: 230,
                ),
              ],
              margin: EdgeInsets.all(5),
            ),
          ],
        );
      };
}

**Comment by bdlukaa** [comment] 2021-04-13 14:52
Have your account been created recently? If yes, make sure it was accepted by admob.

> It could be that you have only recently created a new Ad Unit ID and requesting for live ads. It could take a few hours for ads to start getting served if that is that case.

Don't forget to add your payment information too.

If test ads are working, it's not an issue with the plugin.

**Comment by SureshKumar311** [comment] 2021-04-13 14:56
no the account was created 3 months ago and ads id was created before 5 days 
but i did not add payment info and i dont wheather my account was accepted by admob.

**Comment by bdlukaa** [comment] 2021-04-20 13:28
> real ads are not loading error :3

Well, according to [this](https://github.com/bdlukaa/native_admob_flutter/wiki/Ad-error-codes#load-error-codes), error code 3 means that your request was successful, but no ad was returned due to lack of ad inventory.

**Comment by bdlukaa** [comment] 2021-04-21 13:46
Closing as duplicate of https://github.com/bdlukaa/native_admob_flutter/issues/10

**Closed by bdlukaa** 2021-04-21 13:46 UTC
Labels: duplicate, invalid
